application_settings/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('basket/', include('basket.urls')),
    path('account/', include('account.urls')),
    path('wishlist/', include('wishlist.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_page, name='basket_page'),

    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.WishlistPageView.as_view(), name='wishlist_page'),

    path('add/', views.WishlistAddView.as_view(), name='wishlist_add'),
    path('delete/', views.WishlistDeleteView.as_view(), name='wishlist_delete'),

]

wishlist/models.py
from django.db import models as m

from application_settings import settings
from mainApp.models import Good


class Wishlist(m.Model):
    user = m.ForeignKey(settings.AUTH_USER_MODEL, on_delete=m.CASCADE)
    good = m.ForeignKey(Good, on_delete=m.CASCADE)
    added_date = m.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.good.title

wishlist/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View

from mainApp.models import Good
from wishlist.models import Wishlist


class WishlistPageView(View):
    template_name = 'wishlist/wishlist_page.html'

    def get(self, request):
        context = {
            'items': Wishlist.objects.filter(user=request.user)
        }
        return render(request, self.template_name, context=context)


class WishlistAddView(View):
    def post(self, request):
        if request.POST.get('action') == 'ADD':
            if request.user.is_authenticated:
                wished_item, created = Wishlist.objects.get_or_create(good=Good.objects.get(pk=request.POST.get('goodid')),
                                                                      user=request.user, )

                if not created:
                    wished_item.delete()

                response = JsonResponse({'is_authenticated': True})
            else:
                response = JsonResponse({'is_authenticated': False})

            return response


class WishlistDeleteView(View):
    def post(self, request):
        if request.POST.get('action') == 'DELETE':
            Wishlist.objects.get(good=Good.objects.get(pk=request.POST.get('goodid')), user=request.user).delete()

            return JsonResponse({'items': "OK"})

wishlist/templates/wishlist/wishlist_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="products">
    <div class="container">
      <div class="products__inner">
        <h1>WishList</h1>

        <div class="products__list">
          {% for item in items %}
            {% with good=item.good %}
              {% include 'mainApp/include/_output_good.html' %}
            {% endwith %}
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

  <script>

      Array.from(document.querySelectorAll('.wishlist')).forEach(
          function (item) {
              item.addEventListener('click', function (e) {
                  let currentElement = e.target.parentElement.parentElement.parentElement;
                  if (currentElement.className === 'products__item__inner') {
                      currentElement = currentElement.querySelector('.wishlist')
                  }

                  if (currentElement.className.indexOf('wishlist') !== -1) {
                      e.preventDefault()
                      let currentElementId = currentElement.dataset.id
                      $.ajax({
                          type: 'POST',
                          url: '{% url "wishlist:wishlist_delete" %}',
                          data: {
                              goodid: currentElementId,
                              csrfmiddlewaretoken: "{{csrf_token}}",
                              action: 'DELETE'
                          },
                          success: function (json) {
                              document.querySelector(`#products__item${currentElementId}`).remove()
                          },
                          error: function (xhr, errmsg, err) {
                          }
                      });
                  }
              })
          });
  </script>

{% endblock %}