account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetForm, PwdResetConfirmForm

app_name = 'account'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('register/', views.account_register, name='register'),
    path('login/', views.account_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),

    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),

    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                     success_url='password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),

    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),

    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),

]

application_settings/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('basket/', include('basket.urls')),
    path('account/', include('account.urls')),
    path('wishlist/', include('wishlist.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_page, name='basket_page'),

    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.WishlistPageView.as_view(), name='wishlist_page'),

    path('add/', views.WishlistAddView.as_view(), name='wishlist_add'),
    path('delete/', views.WishlistDeleteView.as_view(), name='wishlist_delete'),

]

templates/include/_header-info.html
<div class="header-info">
  <div class="container">
    <div class="header-info__list">
      <a class="header-info__item">Item - 1</a>
      <a class="header-info__item">Item - 2</a>
      <a class="header-info__item">Item - 3</a>
    </div>
  </div>
</div>

templates/include/_header.html
{% load static %}
<header class="header">
  <div class="container">
    <div class="header__inner">
      <nav class="nav">
        <a href="{% url 'home' %}" class="nav__link">Home</a>
        <a href="{% url 'catalog' %}" class="nav__link">Shop</a>
        <a href="#" class="nav__link">Contact</a>
        <a href="{% url 'account:profile' %}" class="nav__link">Profile
          {% if user.is_authenticated %}
            - {{ user }}
          {% endif %}
        </a>
      </nav>

      <div class="header__right">
        {% if user.is_authenticated %}
          <a href="{% url 'account:logout' %}">Logout</a>
        {% else %}
          <a style="margin-right: 15px;" href="{% url 'account:login' %}">Login</a>
          <a style="margin-right: 15px;" href="{% url 'account:register' %}">Register</a>
        {% endif %}

        <div>

          <div class="header__wishlist">{% csrf_token %}
            <a href="{% url 'wishlist:wishlist_page' %}">
              <img class="header__wishlist" src="{% static 'mainApp/img/heart-black.svg' %}" alt="">
            </a>
          </div>

          <div class="basket">
            <a href="{% url 'basket:basket_page' %}">
              <img src="{% static 'mainApp/img/shopping-cart.svg' %}" alt="">
            </a>
            {% with total_qty=basket|length %}
              <span class="basket__qty">
                {% if total_qty > 0 %}
                  {{ total_qty }}
                {% endif %}
              </span>
            {% endwith %}

          </div>
        </div>
      </div>
    </div>
  </div>
</header>