application_settings/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('basket/', include('basket.urls')),
    path('account/', include('account.urls')),
    path('wishlist/', include('wishlist.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_page, name='basket_page'),

    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

basket/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from basket.basket_class import Basket
from mainApp.models import Good

import json


def basket_page(request):
    return render(request, 'basket/basket_page.html')


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'ADD':
        good_id = int(request.POST.get('goodid'))
        good_qty = int(request.POST.get('goodqty'))
        good = get_object_or_404(Good, id=good_id)

        basket.add(good=good, qty=good_qty)

    basketqty = basket.__len__()
    response = JsonResponse({'qty': basketqty})

    return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'UPDATE':
        goods_data = request.POST.get('goods_data')
        basket.update(json.loads(goods_data))

        id_and_total_price = []

        for id_, value in basket.basket.items():
            id_and_total_price.append({id_: mul([int(i) for i in value.values()])})

        basketqty = basket.__len__()

        response = JsonResponse({'Ids and total prices': id_and_total_price,
                                 'total': basket.get_total_price(),
                                 'qty': basketqty, })
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'DELETE':
        good_id = request.POST.get('goodid')

        basket.delete(good_id=good_id)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})

        return response


def mul(lst):
    m = 1
    for i in lst:
        m = i * m
    return m

basket/templates/basket/basket_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


  <section class="basket__proucts">
    <div class="container">
      <div class="basket__proucts__list">
        {% for item in basket %}
          {% with good=item.good %}
            <div id="basket__item{{ good.pk }}" class="basket__proucts__item">
              <div class="basket__proucts__item__top">
                <div class="basket__proucts__item__top__img ">
                  <a href="{{ good.get_absolute_url }}">
                    <img src="{{ good.photo.url }}" alt="" width="200" height="200">
                  </a>
                </div>
                <div class="basket__proucts__item__top__info">
                  <div class="basket__proucts__item__top__info__title">
                    {{ good.title }}
                  </div>
                  <div class="basket__proucts__item__top__info__subtitle">
                    Description: {{ good.description }}
                  </div>
                </div>
              </div>
              <div class="basket__proucts__item__bottom">
                <button type="button"
                        id="delete-button"
                        data-id="{{ good.pk }}"
                        class="product-btn">
                  Delete
                </button>
                <div style="display: flex; align-items: center">
                  <div class="product-btn" id="product-btn__busket" data-id="{{ good.pk }}">
                    <span id="product-btn__dec{{ good.pk }}" class="product-btn__qty" data-id="{{ good.pk }}">-</span>
                    <input id="input{{ good.pk }}" type="text" value="{{ item.qty }}">
                    <span id="product-btn__inc{{ good.pk }}" class="product-btn__qty" data-id="{{ good.pk }}">+</span>
                  </div>
                  <div id="item__total-price{{ good.pk }}" class="basket__proucts__item__bottom__price">
                    ${{ item.total_price }}
                  </div>
                </div>
              </div>
            </div>
          {% endwith %}
        {% endfor %}
      </div>
      <div class="basket__proucts__bottom">
        <button type="button"
                id="update-button"
                class="product-btn">
          Update Items
        </button>
        <div class="basket__proucts__bottom__total">
          Total: ${{ basket.get_total_price }}
        </div>
      </div>
    </div>
  </section>

  <script>
      $(document).on('click', '#update-button', function (e) {
          e.preventDefault();
          let good_btns = document.querySelectorAll('#product-btn__busket');

          let goods_data = {}

          for (let item of good_btns) {
              let itemid = item.dataset.id
              let qty = item.querySelector(`#input${itemid}`).value

              goods_data[itemid] = {'id': itemid, 'qty': qty}
          }

          $.ajax({
              type: 'POST',
              url: '{% url "basket:basket_update" %}',
              data: {
                  goods_data: JSON.stringify(goods_data),
                  csrfmiddlewaretoken: "{{csrf_token}}",
                  action: 'UPDATE'
              },
              success: function (json) {
                  document.querySelector('.basket__proucts__bottom__total').innerHTML = `$${json['total'].toFixed(1)}`
                  let new_elements = json['Ids and total prices']

                  for (let value of new_elements) {
                      let id = Object.keys(value)[0]
                      let total_price = Object.values(value)[0]
                      document.querySelector(`#item__total-price${id}`).innerHTML = `$${total_price.toFixed(1)}`
                  }

                  document.querySelector(".basket__qty").innerHTML = json.qty
              },
              error: function (xhr, errmsg, err) {
              }
          });
      })

      $(document).on('click', '#delete-button', function (e) {
          e.preventDefault();
          let good_id = this.dataset.id
          $.ajax({
              type: 'POST',
              url: '{% url "basket:basket_delete" %}',
              data: {
                  goodid: good_id,
                  csrfmiddlewaretoken: "{{csrf_token}}",
                  action: 'DELETE'
              },
              success: function (json) {
                  document.querySelector(".basket__qty").innerHTML = json.qty

                  document.querySelector(`#basket__item${good_id}`).remove()
              },
              error: function (xhr, errmsg, err) {
              }
          });
      })
  </script>

{% endblock %}