account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetForm, PwdResetConfirmForm

app_name = 'account'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('register/', views.account_register, name='register'),
    path('login/', views.account_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),

    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),

    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                     success_url='password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),

    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),

    path('password_reset_confirm/Mg/password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),

]

application_settings/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('basket/', include('basket.urls')),
    path('account/', include('account.urls')),
    path('wishlist/', include('wishlist.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_page, name='basket_page'),

    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

mainApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('catalog', views.CatalogListView.as_view(), name='catalog'),
    path('catalog/<slug:slug>', views.CategoryByGenderView.as_view(), name='catalog_sex'),
    path('catalog/<slug:slug_gender>/<slug:slug_category>', views.GoodByCategoryView.as_view(), name='good_by_category'),

    path('good/<slug:slug>', views.GoodDetailView.as_view(), name='good_detail'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.WishlistPageView.as_view(), name='wishlist_page'),

    path('add/', views.WishlistAddView.as_view(), name='wishlist_add'),
    path('delete/', views.WishlistDeleteView.as_view(), name='wishlist_delete'),

]

mainApp/models.py
from django.db import models as m
from django.urls import reverse

from slugify import slugify
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    title = m.CharField(max_length=255, verbose_name="Имя категории", unique=True)
    parent = TreeForeignKey("self", on_delete=m.CASCADE, null=True, blank=True, related_name="children")
    photo = m.ImageField(upload_to="photos/category/%m/%d/", verbose_name="Фото Категорий",
                         default="empty.jfif")

    is_published = m.BooleanField(default=True, verbose_name="Опубликовано ?")

    created_dt = m.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_dt = m.DateTimeField(auto_now=True, verbose_name="Дата оновления")

    slug = m.SlugField(max_length=255, unique=True, blank=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    class MPTTMeta:
        order_insertion_by = ["title"]

    def save(self, *args, **kwargs):
        self.slug = slugify(f"{self.title}")
        parent = self.parent
        print(parent)
        if Good.objects.filter(category=parent).exists():
            raise ValueError("You cann't create categoty if parent has goods")
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Good(m.Model):
    title = m.CharField(max_length=250, verbose_name="Заголовок товара")
    subtitle = m.CharField(max_length=250, verbose_name="Под заголовок товара")
    description = m.TextField(verbose_name="Описание товара", blank=True, null=True)
    price = m.PositiveIntegerField(verbose_name="Цена")
    photo = m.ImageField(upload_to="photos/goods/%m/%d/", verbose_name="Фото товара", default="empty.jfif")
    views = m.PositiveIntegerField(default=0, verbose_name="Количество просмотров")

    is_published = m.BooleanField(default=True, verbose_name="Опулбиковано ?")

    created_dt = m.DateTimeField(auto_now_add=True)
    updated_dt = m.DateTimeField(auto_now=True)

    category = TreeForeignKey(Category, on_delete=m.CASCADE, blank=False,
                              null=False, verbose_name=u'Раздел')

    slug = m.SlugField(max_length=255, unique=True, blank=True)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def save(self, *args, **kwargs):
        if self.category.get_children():
            raise ValueError("It's not last child")
        self.slug = slugify(f"{self.title}")
        super(Good, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('good_detail', kwargs={'slug': self.slug})

mainApp/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView

from .models import Category, Good


class HomeView(View):
    template_name = 'mainApp/home.html'

    def get(self, request, *args, **kwargs):
        filter_value = request.GET.get('filter')
        if filter_value == 'by-date':
            ordered_goods = Good.objects.order_by('-created_dt')[:8]
        elif filter_value == 'by-views':
            ordered_goods = Good.objects.order_by('-views')[:8]
        elif filter_value == 'by-price':
            ordered_goods = Good.objects.order_by('price')[:8]
        else:
            ordered_goods = Good.objects.all()[:8]

        context = {
            "all_goods": ordered_goods
        }
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        pass


class CatalogListView(ListView):
    template_name = 'mainApp/catalog_gender.html'
    context_object_name = 'categories_sex'
    queryset = Category.objects.filter(level=0)


class CategoryByGenderView(View):
    template_name = 'mainApp/goods_by_categories.html'

    def get(self, request, *args, **kwargs):
        slug_gender = self.kwargs['slug']
        categories = Category.objects.get(slug=slug_gender).get_descendants(include_self=False)
        goods = []
        for cat in categories:
            if cat.is_published:
                goods.extend(cat.good_set.filter(is_published=True))

        context = {
            'categories': categories,
            'slug_gender': slug_gender,
            'categories_gender': Category.objects.filter(level=0),
            'goods': goods
        }
        return render(request, self.template_name, context=context)


class GoodByCategoryView(View):
    template_name = 'mainApp/goods_by_categories.html'

    def get(self, request, *args, **kwargs):
        slug_gender = self.kwargs['slug_gender']
        goods = Good.objects.filter(category__slug=self.kwargs['slug_category'], is_published=True)
        categories = Category.objects.get(slug=slug_gender).get_descendants(include_self=False)
        Genders = Category.objects.filter(level=0)

        context = {
            'categories': categories,
            'slug_gender': slug_gender,
            'categories_gender': Genders,
            'goods': goods
        }

        return render(request, self.template_name, context=context)


class GoodDetailView(DetailView):
    template_name = 'mainApp/good_detail.html'
    model = Good

    def dispatch(self, request, *args, **kwargs):
        slug = self.kwargs['slug']
        good = Good.objects.get(slug=slug)
        good.views = good.views + 1
        good.save()
        return super(GoodDetailView, self).dispatch(request, args, kwargs)

mainApp/templates/mainApp/catalog_gender.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="catalog">
    {% for category in categories_sex %}
    <div class="catalog__item" style="background:no-repeat url('{{ category.photo.url }}'); background-size: cover">
      <a href="{% url 'catalog_sex' category.slug %}" class="catalog__btn"><span>{{ category.title }}</span></a>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

mainApp/templates/mainApp/good_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="product-detail">
    <div class="container">
      <div class="product-detail__inner">
        <div class="product-detail__img">
          <img src="{{ good.photo.url }}" alt="" width="100%" height="680">
        </div>
        <div class="product-detail__info">
          <h2 class="product-detail__info__title">
            {{ good.title }}
          </h2>

          <h3 class="product-detail__info__subtitle">
            {{ good.subtitle }}
          </h3>

          <div class="product-detail__info__price">
            ${{ good.price }}
          </div>

          <div>
            <div class="rate">
              <input type="radio" id="star5" name="rate" value="5"/>
              <label for="star5" title="text">5 stars</label>

              <input type="radio" id="star4" name="rate" value="4"/>
              <label for="star4" title="text">4 stars</label>

              <input type="radio" id="star3" name="rate" value="3"/>
              <label for="star3" title="text">3 stars</label>

              <input type="radio" id="star2" name="rate" value="2"/>
              <label for="star2" title="text">2 stars</label>

              <input type="radio" id="star1" name="rate" value="1"/>
              <label for="star1" title="text">1 star</label>
            </div>
          </div>

          <div class="product-detail__info__category">
            Category: {{ good.category }}
          </div>

          <div class="product-detail__info__description">
            Desription: {{ good.description }}
          </div>

          <div class="product-detail__info__btn">
            <div class="product-btn">
              <span id="product-btn__dec" class="product-btn__qty" data-id="{{ good.id }}">-</span>
              <input id="input" type="text" value="1">
              <span id="product-btn__inc" class="product-btn__qty" data-id="{{ good.id }}">+</span>
            </div>
            <button type="button"
                    id="add-button"
                    value="{{ good.pk }}"
                    class="product-btn">
              Add to basket
            </button>
          </div>


        </div>
      </div>
    </div>
  </section>

  <script>
      $(document).on('click', '#add-button', function (e) {
          alert("Products has been added")
          $.ajax({
              type: 'POST',
              url: '{% url "basket:basket_add" %}',
              data: {
                  goodid: $('#add-button').val(),
                  goodqty: $('#input').val(),
                  csrfmiddlewaretoken: "{{csrf_token}}",
                  action: 'ADD'
              },
              success: function (json) {
                  document.querySelector(".basket__qty").innerHTML = json.qty
              },
              error: function (xhr, errmsg, err) {
              }
          });
      })
  </script>
{% endblock %}

mainApp/templates/mainApp/goods_by_categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  {% include 'mainApp/include/_categories.html' %}

  <section class="products">
    <div class="products__error hidden__item"><p>You have to be <a href="{% url "account:login" %}"> logged in</a> to
      add a product to the basket</p></div>
    <div class="container">
      <div class="products__inner">
        <div class="products__filter">
          <ul class="products__control">
            <li class="products__control__item" data-filter="all">All</li>
            <li class="products__control__item" data-filter="by-views">Most popular</li>
            <li class="products__control__item" data-filter="by-price">Biggest price</li>
          </ul>
        </div>
        <div class="products__list">
          {% for good in goods %}
            {% include 'mainApp/include/_output_good.html' %}
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

  <script>
      window.addEventListener("pageshow", function (event) {
          var historyTraversal = event.persisted ||
              (typeof window.performance != "undefined" &&
                  window.performance.navigation.type === 2);
          if (historyTraversal) {
              window.location.reload();
          }
      });

      Array.from(document.querySelectorAll('.wishlist')).forEach(
          function (item) {
              item.addEventListener('click', function (e) {
                  let currentElement = e.target.parentElement.parentElement.parentElement;

                  if (currentElement.className === 'products__item__inner') {
                      currentElement = currentElement.querySelector('.wishlist')
                  }

                  if (currentElement.className.indexOf('wishlist') !== -1) {
                      let currentElementId = currentElement.dataset.id

                      e.preventDefault()
                      $.ajax({
                          type: 'POST',
                          url: '{% url "wishlist:wishlist_add" %}',
                          data: {
                              goodid: currentElementId,
                              csrfmiddlewaretoken: "{{csrf_token}}",
                              action: 'ADD'
                          },
                          success: function (json) {
                              if (json['is_authenticated']) {
                                  currentElement.classList.toggle('wishlist__active')
                              } else {
                                  document.querySelector('.products__error').classList.remove('hidden__item')
                              }
                          },
                          error: function (xhr, errmsg, err) {
                          }
                      });
                  }
              })
          });
  </script>
  <script src="{% static 'mainApp/js/OrderingProducts.js' %}"></script>


{% endblock %}

mainApp/templates/mainApp/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="products">
    <div class="container">
      <div class="products__inner">
        <div class="products__filter">
          <h2 class="products__title">Products</h2>
          <ul class="products__control">
            <li class="products__control__item" data-filter="all">
              <a href="{% url 'home' %}">All</a>
            </li>
            <li class="products__control__item" data-filter="by-date">
              <a href="{% url 'home' %}?filter=by-date">Newest products</a>
            </li>
            <li class="products__control__item" data-filter="by-views">
              <a href="{% url 'home' %}?filter=by-views">Most popular</a>
            </li>
            <li class="products__control__item" data-filter="by-price">
              <a href="{% url 'home' %}?filter=by-price">The cheapest</a>
            </li>
          </ul>
        </div>
        <div class="products__list">
          {% for good in all_goods %}
            {% include 'mainApp/include/_output_good.html' %}
          {% endfor %}
        </div>
      </div>

    </div>
  </section>

  <script>
      window.addEventListener("pageshow", function (event) {
          var historyTraversal = event.persisted ||
              (typeof window.performance != "undefined" &&
                  window.performance.navigation.type === 2);
          if (historyTraversal) {
              window.location.reload();
          }
      });

      Array.from(document.querySelectorAll('.wishlist')).forEach(
          function (item) {
              item.addEventListener('click', function (e) {
                  let currentElement = e.target.parentElement.parentElement.parentElement;

                  if (currentElement.className === 'products__item__inner') {
                      currentElement = currentElement.querySelector('.wishlist')
                  }

                  if (currentElement.className.indexOf('wishlist') !== -1) {
                      let currentElementId = currentElement.dataset.id

                      e.preventDefault()
                      $.ajax({
                          type: 'POST',
                          url: '{% url "wishlist:wishlist_add" %}',
                          data: {
                              goodid: currentElementId,
                              csrfmiddlewaretoken: "{{csrf_token}}",
                              action: 'ADD'
                          },
                          success: function (json) {
                              if (json['is_authenticated']) {
                                  currentElement.classList.toggle('wishlist__active')
                              } else {
                                  document.querySelector('.products__error').classList.remove('hidden__item')
                              }
                          },
                          error: function (xhr, errmsg, err) {
                          }
                      });
                  }
              })
          });
  </script>
{% endblock %}